services:
  net-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: net-app:1.0
    container_name: net-app
    ports:
      - "8080:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: bridge