version: "3.8"
services:
  net-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: net-app:1.0
    container_name: net-app
    ports: 
      - "5000:80"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
