version: "3.9"
services:
  nginx-ws:
    build:
      context: ./
      dockerfile: nginxDockerfile
    image: nginx-ws:1.0
    container_name: nginx-ws
  net-app:
    build:
      context: ./
      dockerfile: weatherDockerfile
    image: net-app:1.0
    container_name: net-app
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
